symbol = "VOO"
option_duration = 40  # How many days until the call option expires when we sell it
strike_step_size = 1  # IMS Is this the strike spacing of the specific asset can we get this from Poloygon?
delta_required = 0.15  # The delta of the option we want to sell
roll_delta_required = 0.15  # The delta of the option we want to sell when we do a roll
maximum_rolls = 2  # The maximum number of rolls we will do
days_before_expiry_to_buy_back = 7  # How many days before expiry to buy back the call
quantity_to_trade = 10  # The number of contracts to trade
minimum_hold_period = 5  # The of number days to wait before exiting a strategy -- this strategy only trades once a day
distance_of_wings = 15  # Distance of the longs from the shorts in dollars -- the wings
budget = 20000  # How close to the short do we allow the price to move before rolling.
strike_roll_distance = 2 # How close to the short do we allow the price to move before rolling.